<h2>Linear programming: </h2>
(1) widely used in engineering (power system network), financial market 

(2) Used to present many practical problem

(3) Elements: A linear objective function 

The standard form 
$$ 
\begin{align}
& \min f(x) \\
\text{s.t} &  ~~ a_1 x \geq b_1\\
& a_2 x + c \geq  b_2\\
& x \geq 0
\end{align}$$

<h2>How to generate a linear model by using gurobipy</h2>

Step 1: importing gurobipy package


In [1]:
from gurobipy import*

Step 2: Create an optimizaiton model by using this package

In this step, we need to explictily model the objective function and its feasibility constraitns.

Model constructor: Initially, there is no varaibles and constraints

In [14]:
opt_model = Model(name="Linear program")

Step 3: add decision variables to a model


Model.addVar(lb = 0, #(optional) lower bound 

ub = float('inf'), #(optional) upper bound

obj = 0.0, #(optional) objective coefficient

vtype = GRB.Continous, #(optional) variable type

name = "" ) #(optional) name

In [15]:
x = opt_model.addVar(name="x", vtype=GRB.CONTINUOUS, lb = 0)
y = opt_model.addVar(name="y", vtype=GRB.CONTINUOUS, lb = 0)

In step 4, we will set the model objective functions and constraints

In [16]:
obj_fn = 2*x + 3*y
opt_model.setObjective(obj_fn, GRB.MINIMIZE)

In [17]:
c1 = opt_model.addConstr(x + y >= 8, name = 'c1')
c2 = opt_model.addConstr(2*x + y >= 10, name = 'c2')
c3 = opt_model.addConstr(x + 4*y >= 11, name = 'c3')



Model_optimize() # optimze the model
Model_write(filename) # write model to a file

In [18]:
opt_model.optimize() # solve the model
opt_model.write("linear_model.lp") # output the model to a file of the model 

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 3 rows, 2 columns and 6 nonzeros
Model fingerprint: 0x63de2d68
Coefficient statistics:
  Matrix range     [1e+00, 4e+00]
  Objective range  [2e+00, 3e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [8e+00, 1e+01]
Presolve time: 0.00s
Presolved: 3 rows, 2 columns, 6 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   1.850000e+01   0.000000e+00      0s
       2    1.7000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds (0.00 work units)
Optimal objective  1.700000000e+01


In [19]:
# output the optimal values of the decision variables

print('Objective value: %f', obj_fn.getValue())
for v in opt_model.getVars():
    print(v.varName, v.x)

Objective value: %f 17.0
x 7.0
y 1.0


In [20]:
for v in opt_model.getVars():
    print('%s %g' % (v.varName, v.x))

print('Obj: %g' % opt_model.objVal)

x 7
y 1
Obj: 17


<h2>Mixed Integer Linear Programming</h2>

In [22]:
# Create a new model
m = Model("mip1")

# Create variables
x = m.addVar(vtype=GRB.BINARY, name="x")
y = m.addVar(vtype=GRB.BINARY, name="y")
z = m.addVar(vtype=GRB.BINARY, name="z")

# Set objective
m.setObjective(x + y + 2 * z, GRB.MAXIMIZE)

# Add constraint: x + 2 y + 3 z <= 4
m.addConstr(x + 2 * y + 3 * z <= 4, "c0")

# Add constraint: x + y >= 1
m.addConstr(x + y >= 1, "c1")

# Optimize model
m.optimize()



Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 2 rows, 3 columns and 5 nonzeros
Model fingerprint: 0x98886187
Variable types: 0 continuous, 3 integer (3 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [1e+00, 2e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 4e+00]
Found heuristic solution: objective 2.0000000
Presolve removed 2 rows and 3 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.00 seconds (0.00 work units)
Thread count was 1 (of 16 available processors)

Solution count 2: 3 2 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.000000000000e+00, best bound 3.000000000000e+00, gap 0.0000%


In [23]:
for v in m.getVars():
    print('%s %g' % (v.varName, v.x))

print('Obj: %g' % m.objVal)

x 1
y 0
z 1
Obj: 3


In [ ]:
# Similarly, we aims to solve the following mixed integer linear programing problem


In [27]:
# Step 1: importing the gurobipy module
from gurobipy import*
# Step 2: Create a model
milp_model = Model(name="Mixed integer linear program")
# Step 3: Create decision variables
x = milp_model.addVar(name="x", vtype=GRB.BINARY)
y = milp_model.addVar(name="y", vtype=GRB.CONTINUOUS, lb = 0)
z = milp_model.addVar(name="z", vtype=GRB.INTEGER, lb = 0)

# Step 4: Set the objective function
obj_fn = 2*x + y + 3*z
milp_model.setObjective(obj_fn, GRB.MAXIMIZE)
# Add constraints

C1 = milp_model.addConstr(x + 2*y + z <= 4, name = 'C1')
C2 = milp_model.addConstr(2 *z + y <= 5, name = 'C2')
C3 = milp_model.addConstr(x + y >= 1, name = 'C3')


# solve the model
milp_model.optimize() 

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 3 rows, 3 columns and 7 nonzeros
Model fingerprint: 0x8a1c7e4e
Variable types: 1 continuous, 2 integer (1 binary)
Coefficient statistics:
  Matrix range     [1e+00, 2e+00]
  Objective range  [1e+00, 3e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 5e+00]
Found heuristic solution: objective 3.5000000
Presolve removed 3 rows and 3 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 16 available processors)

Solution count 2: 8.5 3.5 

Optimal solution found (tolerance 1.00e-04)
Best objective 8.500000000000e+00, best bound 8.500000000000e+00, gap 0.0000%


In [31]:
# print results
print('objective value: %.2f ' % obj_fn.getValue())
for v in milp_model.getVars():
    print('%s %g' % (v.varName, v.x))

objective value: 8.50 
x 1
y 0.5
z 2


<h2>Integer Linear Programming</h2>

When decision variables are multi-dimensional, we may need to use `for` loop to express it. In the following, we use binary knapsack problem (Integer programming) to take an example


<h2>Binary knapsack problem</h2>

* Combinatorial optimization problem
* Problem of pakcing the most valuable or useful items without overloading the luggage.
    * A set of items ($N$ items), each with a weight ($w$) and a value ($v$)
    * Maximize the total value possible
    * Fixed capacity
    

\begin{align}
    & maximize ~ \sum_{i = 1}^{N} v_i x_i \\
    & \text{s.t} ~ \sum_{i = 1}^{N} w_i x_i \leq C \\
    & x_i \in \{0,1\}, ~ \forall i = 1,2,3,4,\dots,N
\end{align}

In [37]:
# Create data: (Cost parameter, weight, value, capacity, number of items)
w = [4,2,5,4,5,1,3,5]
v = [10,5,18,12,15,1,2,8]
C = 15
N = len(w)

# Importing Gurobipy package

from gurobipy import*

knapsack_model = Model(name="Knapsack problem")
x = knapsack_model.addVars(N, vtype=GRB.BINARY, name="x")
obj_fn = quicksum(v[i]*x[i] for i in range(N))
knapsack_model.setObjective(obj_fn, GRB.MAXIMIZE)
knapsack_model.addConstr(quicksum(w[i]*x[i] for i in range(N)) <= C)
knapsack_model.setParam('OutputFlag', False)
knapsack_model.optimize()

print('Objective value: %f' % obj_fn.getValue())
for v in knapsack_model.getVars():
    print(v.varName, v.x)

Objective value: 46.000000
x[0] 0.0
x[1] 0.0
x[2] 1.0
x[3] 1.0
x[4] 1.0
x[5] 1.0
x[6] 0.0
x[7] 0.0


<h2>Quadratic programming</h2>

 * **Quadratic programming was developed in 1950s**
 * Widely used in 
    * optimization of financial portfolios 
    * Image and signal processing
    * Regression
    * Scheduling in chemical plants etc
+ **Solution method**
    + Integrior point
    + Augmented Lagrange
    + Gradient-based 
    + Extensions of the simplex algorithm


\begin{align}
    & \min \frac{1}{2} x^{T} Q x + c^{T} x \\
    & \text{s.t} Ax \leq b
\end{align}

where $c \in \mathbb{R}^{n}$, $Q \in \mathbb{R}^{n \times n}$, $A \in \mathbb{R}^{m \times n}$, $b \in \mathbb{R}^{m}$

<h2>Coding in python</h2>

The model:


\begin{align}
    & \min \frac{1}{2} z^2 + 2 y^{2} + x^{2} \\
    & \text{s.t} x + 3y + 2z \geq 5\\
    & y + z \geq 2.5\\
    & x,y \geq 0 \\
    & y \in \mathbb{Z} \\
    & z \in \{0,1\}
\end{align}


In [42]:
quadra_model = Model(name="Quadratic program")

x = quadra_model.addVar(name="x", vtype=GRB.CONTINUOUS, lb = 0)
y = quadra_model.addVar(name="y", vtype=GRB.INTEGER, lb = 0)
z = quadra_model.addVar(name="z", vtype=GRB.BINARY)

obj_fn = 1/2 * z**2 + x**2 + 2*y**2
quadra_model.setObjective(obj_fn, GRB.MINIMIZE)
c1 = quadra_model.addConstr(x + 3*y + 2*z >= 5, name = 'c1')
c2 = quadra_model.addConstr(y + z >= 2.5, name = 'c2')
quadra_model.setParam('OutputFlag', False)
quadra_model.optimize() # solve the model

print('Objective value: %f' % obj_fn.getValue())
for v in quadra_model.getVars():
    print(v.varName, v.x)

Objective value: 8.500000
x 0.0
y 2.0
z 1.0


In [47]:
# If addding another quadratic constraint
quadra_model = Model(name="Quadratic program")

x = quadra_model.addVar(name="x", vtype=GRB.CONTINUOUS, lb = 0)
y = quadra_model.addVar(name="y", vtype=GRB.CONTINUOUS, lb = 0)
z = quadra_model.addVar(name="z", vtype=GRB.BINARY)

obj_fn = 1/2 * z**2 + x**2 + 2*y**2
quadra_model.setObjective(obj_fn, GRB.MINIMIZE)
c1 = quadra_model.addConstr(x + 3*y + 2*z >= 5, name = 'c1')
c2 = quadra_model.addConstr(y + z >= 2.5, name = 'c2')
quadra_model.setParam('OutputFlag', False)
quadra_model.optimize() # solve the model

print('Objective value: %f' % obj_fn.getValue())
for v in quadra_model.getVars():
    print(v.varName, v.x)


Objective value: 5.000000
x 0.0
y 1.5
z 1.0


In [49]:
# If addding another quadratic constraint
quadra_model = Model(name="Quadratic program")

x = quadra_model.addVar(name="x", vtype=GRB.CONTINUOUS, lb = 0)
y = quadra_model.addVar(name="y", vtype=GRB.CONTINUOUS, lb = 0)
z = quadra_model.addVar(name="z", vtype=GRB.BINARY)

obj_fn = 1/2 * z**2 + x**2 + 2*y**2
quadra_model.setObjective(obj_fn, GRB.MINIMIZE)
c1 = quadra_model.addConstr(x + 3*y + 2*z >= 5, name = 'c1')
c2 = quadra_model.addConstr(y + z >= 2.5, name = 'c2')
# c3 = quadra_model.addConstr(z**2 + y**2 <= x**2, name = 'c3')

quadra_model.setParam('OutputFlag', False)
quadra_model.optimize() # solve the model

print('Objective value: %f' % obj_fn.getValue())
for v in quadra_model.getVars():
    print(v.varName, v.x)

Objective value: 5.000000
x 0.0
y 1.5
z 1.0


In [51]:
quadra_model.addConstr(z**2 + y**2 <= x**2, name = 'c3')
quadra_model.optimize() # solve the model

print('Objective value: %f' % obj_fn.getValue())
for v in quadra_model.getVars():
    print(v.varName, v.x)


Objective value: 8.250000
x 1.8027756402615691
y 1.4999999999858802
z 1.0


<h2>Linear assignment</h2>

<h2>Mathematical Formulation</h2>


\begin{align}
    & \min_{x} ~ \sum_{i}^{n} \sum_{n} c_{i,j} x_{i,j} \\
    & \text{s.t} ~~ \sum_i^{n} x_{i,j} \leq 1, ~ \forall j = 1, \dots n \\
    & \sum_i^{n} x_{j} = 1, ~ \forall i = 1, \dots n \\
    & x_{i,j} \in \{0,1\}, \forall i,j
\end{align}

where $x_{i,j} = 1$ means worker $i performs task $j$, 0 otherwise. Now we are ready to implemtn the following problem as follows:


In [57]:
# step 1: import the gurobipy module

from gurobipy import Model, GRB
import numpy as np

# generate cost parameter, which is integer value from 1 to 10 with dimension 4 by 4
cost = np.random.randint(1, 10, [4,4])
print(cost)

assignment_model = Model('Assignment problem')

# Step 3: Create decision variables
# first two arguments are the dimension of the decision variables
# vtype=GRB.BINARY means the decision variables are binary
# name="x" is the name of the decision variables
x = assignment_model.addVars(cost.shape[0], cost.shape[1], vtype=GRB.BINARY, name="x")

# step 4: Set the objective function
obj_fn = sum(cost[i,j] * x[i,j] for i in range(cost.shape[0]) for j in range(cost.shape[1]))
assignment_model.setObjective(obj_fn, GRB.MINIMIZE)

# step 5: Add constraints
# sum_{j = 1}^{n}  x_{i,j} <= 1 for i = 1, 2, ..., n
assignment_model.addConstrs((sum(x[i,j] for i in range(cost.shape[0])) <= 1 for j in range(cost.shape[1])), name = 'workload')
# sum_{i = 1}^{n}  x_{i,j} <= 1 for j = 1, 2, ..., n
assignment_model.addConstrs((sum(x[i,j] for j in range(cost.shape[1])) == 1 for i in range(cost.shape[0])), name = 'assignment')

assignment_model.setParam('OutputFlag', True)
assignment_model.optimize()

print('Model Statistics')

print('Objective value: %f' % obj_fn.getValue())
print('\n\n Model Output \n')
print(assignment_model.display())

[[8 4 2 2]
 [2 1 5 5]
 [4 2 6 9]
 [4 1 4 2]]
Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 8 rows, 16 columns and 32 nonzeros
Model fingerprint: 0xe79a4aef
Variable types: 0 continuous, 16 integer (16 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 9e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 8.0000000
Presolve removed 0 rows and 1 columns
Presolve time: 0.00s
Presolved: 8 rows, 15 columns, 30 nonzeros
Variable types: 0 continuous, 15 integer (15 binary)

Root relaxation: cutoff, 5 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node T

In [48]:
print('Objective value: %f' % assignment_model.objVal)

for v in assignment_model.getVars():
    print('%s %g' % (v.varName, v.x))

Objective value: 14.000000
x[0,0] 1
x[0,1] 0
x[0,2] -0
x[0,3] 0
x[1,0] -0
x[1,1] -0
x[1,2] 1
x[1,3] -0
x[2,0] -0
x[2,1] 1
x[2,2] 0
x[2,3] -0
x[3,0] -0
x[3,1] -0
x[3,2] -0
x[3,3] 1


In [59]:
# step 1: import the gurobipy module

assignment_model_new = Model('Assignment')

# Step 3: Create decision variables
# first two arguments are the dimension of the decision variables
# vtype=GRB.BINARY means the decision variables are binary
# name="x" is the name of the decision variables
y = assignment_model_new.addVars(cost.shape[0], cost.shape[1], vtype=GRB.CONTINUOUS, lb = 0, ub = 1, name="y")

# step 4: Set the objective function
obj_fn = sum(cost[i,j] * y[i,j] for i in range(cost.shape[0]) for j in range(cost.shape[1]))
assignment_model_new.setObjective(obj_fn, GRB.MINIMIZE)

# step 5: Add constraints
# sum_{j = 1}^{n}  y_{i,j} <= 1 for i = 1, 2, ..., n
assignment_model_new.addConstrs((sum(y[i,j] for i in range(cost.shape[0])) <= 1 for j in range(cost.shape[1])), name = 'workload_constr')
# sum_{i = 1}^{n}  y_{i,j} <= 1 for j = 1, 2, ..., n
assignment_model_new.addConstrs((sum(y[i,j] for j in range(cost.shape[1])) == 1 for i in range(cost.shape[0])), name = 'assignment_constr')

assignment_model_new.setParam('OutputFlag', True)
assignment_model_new.optimize()

print('Model Statistics')
print('Objective value: %f' % obj_fn.getValue())
print('\n\n Model Output \n')
print(assignment_model_new.display())


Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 8 rows, 16 columns and 32 nonzeros
Model fingerprint: 0xc388a71f
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 9e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve time: 0.00s
Presolved: 8 rows, 16 columns, 32 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    6.0000000e+00   2.000000e+00   0.000000e+00      0s
       2    8.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds (0.00 work units)
Optimal objective  8.000000000e+00
Model Statistics
Objective value: 8.000000


 Model Output 

Minimize
8.0 y[0,0] + 4.0 y[0,1] + 2.0 y[0,2] + 2.0 y[0,3] + 2.0 y[1,0] + y[1,1] + 5.0 y[1,2]
+ 5.0 y[1,3

In [67]:
print('Objective value: %f' % assignment_model_new.objVal)

for v in assignment_model_new.getVars():
    print('%s %g' % (v.varName, v.x))

Objective value: 8.000000
y[0,0] 0
y[0,1] 0
y[0,2] 1
y[0,3] 0
y[1,0] 1
y[1,1] 0
y[1,2] 0
y[1,3] 0
y[2,0] 0
y[2,1] 1
y[2,2] 0
y[2,3] 0
y[3,0] 0
y[3,1] 0
y[3,2] 0
y[3,3] 1
